### ISSUE TITLE
Error in encode.h?

### ISSUE THREAD

**Issue by ericklil** [jmechnich/ledlamp#1]
Hello, I seem to be getting the following error upon compiling..

> RotaryLED2.ino:7:0:
encoder.h:39: error: invalid use of destructor '~Encoder' as a type
   ~Encoder
   ^
exit status 1
invalid use of destructor '~Encoder' as a type

Any clues or help would be marvelous, Many Thanks

**Comment by jmechnich** [comment]
Sorry for replying that late but I had (and still have) no suggestion other than looking for an error in your build setup.

Closing due to age.
